# Generated by Django 5.0.3 on 2024-03-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nieruchomosci',
            fields=[
                ('ID_nieruchomosci', models.AutoField(primary_key=True, serialize=False)),
                ('ID_adresu', models.IntegerField()),
                ('Powierzchnia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Liczba_pokoi', models.IntegerField()),
                ('Cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(max_length=50)),
                ('Typ_nieruchomosci', models.CharField(max_length=50)),
                ('Opis', models.TextField()),
            ],
        ),
    ]
